POST http://localhost:3002/api/blogs
Content-Type: application/json

{
  "title": "Testiblogi3",
  "author": "Testi Testi3",
  "url": "www.testi.fi",
  "likes": 0,
  "userId": "620f871a62a51822499990b7"
}